name: Scheduled Android Tests

on:
  schedule:
    # 03:00 every Sunday
    - cron: '0 3 * * 0'
  workflow_dispatch:

concurrency:
  group: scheduled-android-tests
  cancel-in-progress: true

env:
  FORCE_COLOR: '1'

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: androidtodo
            millargs: example.thirdparty.androidtodo.packaged.daemon
            setup-android: true
          - name: android-endless-tunnel
            millargs: example.thirdparty.android-endless-tunnel.packaged.daemon
            setup-android: true
    name: Android / ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: ./.github/actions/setup-android
      - uses: coursier/cache-action@v8
      - name: Run example
        run: ./mill show ${{ matrix.millargs }}
