name: Scheduled Android Tests

on:
  schedule:
    # 03:00 every Sunday
    - cron: '0 3 * * 0'
  workflow_dispatch:

concurrency:
  group: scheduled-android-tests
  cancel-in-progress: true

env:
  FORCE_COLOR: '1'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pre-build-setup
        with:
          os: ubuntu-latest
          java-version: 21
          shell: bash
          prepareargs: 'example.thirdparty.{androidtodo,android-endless-tunnel}.packaged.daemon'
      - uses: actions/upload-artifact@v6.0.0
        with:
          path: .
          name: ubuntu-latest-artifact
          include-hidden-files: true
  android:
    needs: build-linux
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: androidtodo
            millargs: example.thirdparty.androidtodo.packaged.daemon
            setup-android: true
          - name: android-endless-tunnel
            millargs: example.thirdparty.android-endless-tunnel.packaged.daemon
            setup-android: true
    name: Android / ${{ matrix.name }}
    uses: ./.github/workflows/post-build-selective.yml
    with:
      setup-android: ${{ matrix.setup-android }}
      java-version: 21
      millargs: ${{ matrix.millargs }}
      shell: bash
